[package]
name = "git-sync"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
octocrab = "0.48.1"
tokio = { version = "1.48.0", features = ["full"] }

[[bin]]
name = "git-sync"
path = "src/main.rs"